services:
  shopsync.inventoryservice:
    image: ${DOCKER_REGISTRY-}shopsyncinventoryservice
    build:
      context: ..
      dockerfile: ShopSync.InventoryService/Dockerfile # Üst klasöre çıkıp InventoryService'e girer
    container_name: shopsync-inventory
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Log ve Metrik Ayarları
      - Loki__Url=http://loki:3100
      - Otlp__Endpoint=http://jaeger:4317
      # Veritabanı ve Kilit Ayarları (Docker içindeki servis adlarıyla)
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=shopSync_inventory
      - RedisSettings__ConnectionString=redis:6379
    depends_on:
      - mongodb
      - redis
      - loki
      - prometheus
      - jaeger

  # ---- VERİTABANI (Zorunlu) ----
  mongodb:
    image: mongo:7.0
    container_name: shopsync-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # Transaction için Replica Set ŞART!
    command: mongod --replSet rs0

  # Mongo Replica Set'i otomatik başlatan init job
  mongo-init-replica:
    image: mongo:7.0
    container_name: shopsync-mongo-init
    depends_on:
      - mongodb
    entrypoint: >
      bash -c "
        echo 'Waiting for MongoDB to start...';
        sleep 5;
        mongosh --host mongodb --eval '
          try {
            rs.initiate({ _id: \"rs0\", members: [{ _id: 0, host: \"mongodb:27017\" }] });
            print(\"Replica Set initialized successfully.\");
          } catch(e) {
            print(\"Replica Set already initialized or error: \" + e);
          }
        ';
      "

  # ---- REDIS (Zorunlu - Distributed Lock için) ----
  redis:
    image: redis:7.2-alpine
    container_name: shopsync-redis
    ports:
      - "6379:6379"

  # ---- LOKI (Log Deposu) ----
  loki:
    image: grafana/loki:latest
    container_name: shopsync-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # ---- PROMETHEUS (Metrik Deposu) ----
  prometheus:
    image: prom/prometheus:latest
    container_name: shopsync-prometheus
    ports:
      - "9090:9090"

  # ---- JAEGER (Tracing - İzleme) ----
  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: shopsync-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"

  # ---- GRAFANA (Görselleştirme Arayüzü) ----
  grafana:
    image: grafana/grafana:latest
    container_name: shopsync-grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
      - jaeger

volumes:
  mongodb_data:
